const games = [
  {
    title: 'Grand Theft Auto V',
    description: 'Open-world crime sandbox with driving, shooting, and deep side activities. The definitive Los Santos experience with hundreds of hours of content.',
    genre: 'Action',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg',
    bannerUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/page_bg_generated_v6b.jpg',
    rating: 9.5,
    trailerUrl: 'QkkoHAzjnUs',
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-3470', ram: '8 GB', gpu: 'NVIDIA GTX 660', storage: '92 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/271590/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/271590/', android: '', ios: '', console: 'https://www.rockstargames.com/gta-v' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['multiplayer', 'open-world', 'crime', 'action'],
    isFree: false, price: '$29.99', developer: 'Rockstar North', publisher: 'Rockstar Games', releaseYear: 2015, views: 12000, isTrending: true,
    screenshots: [
      'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_254c9217b5e2a6d6edd8571c64bfab0b6ccfbfd3.jpg',
      'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_3a5a7cd36e0dfe7eaa75c68c9b04e4c0d8c0b1d0.jpg',
    ],
  },
  {
    title: 'Cyberpunk 2077',
    description: 'Futuristic open-world RPG with fast-paced combat and deep story choices. Explore the vibrant Night City in this award-winning epic.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
    bannerUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/page_bg_generated_v6b.jpg',
    rating: 9.0,
    trailerUrl: 'BO8lX3hDU30',
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i7-6700K', ram: '12 GB', gpu: 'NVIDIA GTX 1060', storage: '70 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1091500/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/1091500/', android: '', ios: '', console: 'https://www.cyberpunk.net' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['open-world', 'RPG', 'futuristic', 'singleplayer'],
    isFree: false, price: '$59.99', developer: 'CD Projekt Red', publisher: 'CD Projekt', releaseYear: 2020, views: 9500, isTrending: true,
    screenshots: [
      'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_b529b0abc43f55fc23977e38c3ad4ef5b87da8e1.jpg',
    ],
  },
  {
    title: 'Elden Ring',
    description: 'Souls-style open-world RPG with deep lore, punishing combat, and breathtaking exploration. Rise, Tarnished, and become the Elden Lord.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
    bannerUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/page_bg_generated_v6b.jpg',
    rating: 9.7,
    trailerUrl: 'E3Huy2cdih0',
    systemRequirements: { os: 'Windows 10/11', cpu: 'Intel Core i5-8400', ram: '12 GB', gpu: 'NVIDIA GTX 1060', storage: '60 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1245620/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/1245620/', android: '', ios: '', console: 'https://www.bandainamcoent.com/games/elden-ring' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['multiplayer', 'open-world', 'souls-like', 'difficult'],
    isFree: false, price: '$59.99', developer: 'FromSoftware', publisher: 'Bandai Namco', releaseYear: 2022, views: 13000, isTrending: true,
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1245620/ss_e80a907c2c43337e53316c71555c3501b9e5f34e.jpg',
    ],
  },
  {
    title: 'Valorant',
    description: '5v5 hero-based tactical shooter where precise gunplay meets unique agent abilities. Free to play, forever competitive.',
    genre: 'Shooter',
    platform: ['PC'],
    imageUrl: 'https://cmsassets.rgpub.io/sanity/images/dsfx7636/news/ea9e6da6b0e2f1e1fc38e78d6b36e2bc5a5d4b00-1920x1080.jpg',
    rating: 9.0,
    trailerUrl: 'e_E7MnMFKNg',
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel i3-4150', ram: '4 GB', gpu: 'NVIDIA GT 730', storage: '30 GB' },
    officialDownloadLink: 'https://playvalorant.com/',
    downloadLinks: { pc: 'https://playvalorant.com/', android: '', ios: '', console: '' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['free', 'multiplayer', 'competitive', 'tactical'],
    isFree: true, price: 'Free', developer: 'Riot Games', publisher: 'Riot Games', releaseYear: 2020, views: 15500, isTrending: true,
    screenshots: [],
  },
  {
    title: 'Genshin Impact',
    description: 'Anime-style open-world action RPG with gacha mechanics and stunning co-op exploration across the vast world of Teyvat.',
    genre: 'RPG',
    platform: ['PC', 'Mobile', 'Console', 'Cross-Platform'],
    imageUrl: 'https://fastcdn.hoyoverse.com/content-v2/nap/116424/7c16d01db85bb95af3e5e2c4ded6c9b5_5481484069671562406.jpg',
    rating: 8.7,
    trailerUrl: 'TToiOHEFXkI',
    systemRequirements: { os: 'Windows 7 SP1 64-bit', cpu: 'Intel Core i7', ram: '16 GB', gpu: 'NVIDIA GTX 1060', storage: '30 GB' },
    officialDownloadLink: 'https://genshin.hoyoverse.com/',
    downloadLinks: { pc: 'https://genshin.hoyoverse.com/en/download', android: 'https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact', ios: 'https://apps.apple.com/app/genshin-impact/id1517783697', console: 'https://genshin.hoyoverse.com/' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['free', 'multiplayer', 'open-world', 'anime'],
    isFree: true, price: 'Free', developer: 'miHoYo', publisher: 'HoYoverse', releaseYear: 2020, views: 15000, isTrending: true,
    screenshots: [],
  },
  {
    title: 'PUBG Mobile',
    description: 'Mobile-focused battle-royale shooter set in massive open maps. Drop in, scavenge, and be the last one standing.',
    genre: 'Battle Royale',
    platform: ['Mobile'],
    imageUrl: 'https://play-lh.googleusercontent.com/JRd0v_H_tI17sEEO_2_B68wSndGvVdaq19-F_mreP8DVsYw.jpg',
    rating: 8.4,
    trailerUrl: 'CanGsz_2PQM',
    systemRequirements: { os: 'Android 5.1 / iOS 11', cpu: 'Snapdragon 625', ram: '2 GB', gpu: 'Any', storage: '2 GB' },
    officialDownloadLink: 'https://play.google.com/store/apps/details?id=com.tencent.ig',
    downloadLinks: { pc: '', android: 'https://play.google.com/store/apps/details?id=com.tencent.ig', ios: 'https://apps.apple.com/app/pubg-mobile/id1330123889', console: '' },
    downloadSource: 'Play Store',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['free', 'multiplayer', 'battle-royale', 'mobile'],
    isFree: true, price: 'Free', developer: 'LightSpeed & Quantum Studio', publisher: 'Tencent Games', releaseYear: 2018, views: 11000,
    screenshots: [],
  },
  {
    title: 'Forza Horizon 5',
    description: 'Vibrant open-world racing festival set in the heart of Mexico. Hundreds of cars, events, and online modes await.',
    genre: 'Racing',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg',
    rating: 9.3,
    trailerUrl: 'FYH9n37B7Yw',
    systemRequirements: { os: 'Windows 10', cpu: 'Intel i5-4460', ram: '8 GB', gpu: 'NVIDIA GTX 970', storage: '110 GB' },
    officialDownloadLink: 'https://www.xbox.com/en-US/games/forza-horizon-5',
    downloadLinks: { pc: 'https://store.steampowered.com/app/1551360/', android: '', ios: '', console: 'https://www.xbox.com/en-US/games/forza-horizon-5' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['multiplayer', 'open-world', 'racing', 'cars'],
    isFree: false, price: '$59.99', developer: 'Playground Games', publisher: 'Xbox Game Studios', releaseYear: 2021, views: 11500,
    screenshots: [],
  },
  {
    title: 'Rocket League',
    description: 'Soccer with rocket-powered cars! High-flying, competitive cross-platform action that anyone can pick up but takes years to master.',
    genre: 'Sports',
    platform: ['PC', 'Console', 'Cross-Platform'],
    imageUrl: 'https://cdn2.unrealengine.com/rocket-league-1920x1080-1920x1080-971712992.jpg',
    rating: 9.1,
    trailerUrl: 'om2ztQqtras',
    systemRequirements: { os: 'Windows 7 or later', cpu: '2.5 GHz Dual Core', ram: '4 GB', gpu: 'NVIDIA GTX 760', storage: '20 GB' },
    officialDownloadLink: 'https://www.rocketleague.com/',
    downloadLinks: { pc: 'https://www.epicgames.com/store/p/rocket-league', android: '', ios: '', console: 'https://www.rocketleague.com/' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['free', 'multiplayer', 'competitive', 'sports'],
    isFree: true, price: 'Free', developer: 'Psyonix', publisher: 'Psyonix', releaseYear: 2015, views: 13000,
    screenshots: [],
  },
  {
    title: 'Hollow Knight',
    description: 'Challenging 2D Metroidvania with gorgeous hand-drawn art. Explore a vast underground kingdom of insects and fallen heroes.',
    genre: 'Indie',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
    rating: 9.6,
    trailerUrl: 'UAO2urG23S4',
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core i5', ram: '4 GB', gpu: 'NVIDIA GTX 560', storage: '9 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/367520/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/367520/', android: '', ios: '', console: 'https://www.nintendo.com/store/products/hollow-knight-switch/' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['singleplayer', 'metroidvania', 'difficult', 'low-end'],
    isFree: false, price: '$14.99', developer: 'Team Cherry', publisher: 'Team Cherry', releaseYear: 2017, views: 9200,
    screenshots: [],
  },
  {
    title: 'The Witcher 3: Wild Hunt',
    description: 'The greatest RPG ever made. A vast open world full of morally complex choices, stunning side quests, and unforgettable characters.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
    rating: 9.8,
    trailerUrl: 'c0i88t0Kacs',
    systemRequirements: { os: 'Windows 7/8/10', cpu: 'Intel Core i5-2500K', ram: '6 GB', gpu: 'NVIDIA GTX 660', storage: '50 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/292030/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/292030/', android: '', ios: '', console: 'https://www.gog.com/game/the_witcher_3_wild_hunt' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['singleplayer', 'open-world', 'story-rich', 'fantasy'],
    isFree: false, price: '$39.99', developer: 'CD Projekt Red', publisher: 'CD Projekt', releaseYear: 2015, views: 10500,
    screenshots: [],
  },
  {
    title: 'Call of Duty: Warzone',
    description: 'Large-scale free-to-play battle-royale within the CoD universe. Drop into Verdansk with 150 players and fight to survive.',
    genre: 'Battle Royale',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1962660/header.jpg',
    rating: 8.2,
    trailerUrl: 'Y2BNSMzL6bU',
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i3-6100', ram: '8 GB', gpu: 'NVIDIA GTX 960', storage: '125 GB' },
    officialDownloadLink: 'https://www.callofduty.com/warzone',
    downloadLinks: { pc: 'https://www.callofduty.com/warzone', android: '', ios: '', console: 'https://www.callofduty.com/warzone' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['free', 'multiplayer', 'battle-royale', 'shooter'],
    isFree: true, price: 'Free', developer: 'Infinity Ward', publisher: 'Activision', releaseYear: 2020, views: 14000,
    screenshots: [],
  },
  {
    title: 'Hades',
    description: 'Fast-paced roguelike dungeon-crawler with incredible writing and stylish combat. Defy the god of the dead and escape the Underworld.',
    genre: 'Action',
    platform: ['PC', 'Console', 'Mobile'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
    rating: 9.8,
    trailerUrl: 'QbZFMCBLiDQ',
    systemRequirements: { os: 'Windows 7 SP1', cpu: 'Intel Core i5-2400', ram: '8 GB', gpu: 'NVIDIA GTX 850M', storage: '15 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1145360/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/1145360/', android: 'https://play.google.com/store/apps/details?id=com.supergiantgames.hades', ios: 'https://apps.apple.com/app/hades/id1445775538', console: 'https://www.nintendo.com/store/products/hades-switch/' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['roguelike', 'singleplayer', 'offline', 'indie'],
    isFree: false, price: '$24.99', developer: 'Supergiant Games', publisher: 'Supergiant Games', releaseYear: 2020, views: 8800,
    screenshots: [],
  },
  {
    title: 'Minecraft',
    description: 'The best-selling game of all time. Build, explore, and survive in an infinite procedurally generated world of blocks.',
    genre: 'Simulation',
    platform: ['PC', 'Mobile', 'Console', 'Cross-Platform'],
    imageUrl: 'https://www.minecraft.net/content/dam/games/minecraft/key-art/MC-Vanilla_Block-World_1280x768.jpg',
    rating: 9.5,
    trailerUrl: 'MmB9b5njVbA',
    systemRequirements: { os: 'Windows 10', cpu: 'Intel Core i5', ram: '8 GB', gpu: 'NVIDIA GTX 700', storage: '4 GB' },
    officialDownloadLink: 'https://www.minecraft.net/en-us/get-minecraft',
    downloadLinks: { pc: 'https://www.minecraft.net/en-us/get-minecraft', android: 'https://play.google.com/store/apps/details?id=com.mojang.minecraftpe', ios: 'https://apps.apple.com/app/minecraft/id479516143', console: 'https://www.minecraft.net/en-us/get-minecraft' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['multiplayer', 'singleplayer', 'sandbox', 'survival', 'low-end'],
    isFree: false, price: '$26.95', developer: 'Mojang Studios', publisher: 'Xbox Game Studios', releaseYear: 2011, views: 20000, isTrending: true,
    screenshots: [],
  },
  {
    title: 'Free Fire',
    description: 'Fast-paced mobile battle royale. 50 players, 10-minute matches, intense survival gameplay designed for mobile.',
    genre: 'Battle Royale',
    platform: ['Mobile'],
    imageUrl: 'https://play-lh.googleusercontent.com/X0dBuP5VFRgkZrJYnxLzCVsFT3n5RJa2PCJL8IBTFBMS0K9dMMYLHBq9x3dJNnkGwA',
    rating: 8.0,
    trailerUrl: 'Ig6JIEPiDmE',
    systemRequirements: { os: 'Android 4.1 / iOS 9.0', cpu: 'Any Quad-core', ram: '1 GB', gpu: 'Any', storage: '1.5 GB' },
    officialDownloadLink: 'https://play.google.com/store/apps/details?id=com.dts.freefireth',
    downloadLinks: { pc: '', android: 'https://play.google.com/store/apps/details?id=com.dts.freefireth', ios: 'https://apps.apple.com/app/garena-free-fire/id1300146617', console: '' },
    downloadSource: 'Play Store',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['free', 'multiplayer', 'battle-royale', 'mobile'],
    isFree: true, price: 'Free', developer: '111dots Studio', publisher: 'Garena', releaseYear: 2017, views: 18000,
    screenshots: [],
  },
  {
    title: 'Grand Theft Auto VI',
    description: 'The most anticipated game of the decade. Return to Vice City for a new generation of open-world crime and chaos.',
    genre: 'Action',
    platform: ['Console', 'PC'],
    imageUrl: 'https://media-rockstargames-com.akamaized.net/tina-uploads/posts/69r1b3kaa74b77/8f6e27f0adff37da5aac6b19dfe4ef9b3af37e5a.jpg',
    rating: 9.9,
    trailerUrl: 'QdBZExpgErs',
    systemRequirements: { os: 'Windows 11', cpu: 'Intel Core i9-12900K', ram: '32 GB', gpu: 'NVIDIA RTX 4080', storage: '200 GB' },
    officialDownloadLink: 'https://www.rockstargames.com/VI',
    downloadLinks: { pc: 'https://www.rockstargames.com/VI', android: '', ios: '', console: 'https://www.rockstargames.com/VI' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['multiplayer', 'open-world', 'next-gen', 'trending'],
    isFree: false, price: '$79.99', developer: 'Rockstar Games', publisher: 'Rockstar Games', releaseYear: 2026, views: 100000, isTrending: true,
    screenshots: [],
  },
  {
    title: 'Celeste',
    description: 'Brutally hard yet rewarding pixel-art platformer with an emotional story about climbing a mountain — and overcoming yourself.',
    genre: 'Indie',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg',
    rating: 9.5,
    trailerUrl: '70d9irlxiB4',
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core i3 @ 2.0 GHz', ram: '2 GB', gpu: 'Intel HD 4000', storage: '1.2 GB' },
    officialDownloadLink: 'http://www.celestegame.com/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/504230/', android: '', ios: '', console: 'https://www.nintendo.com/store/products/celeste-switch/' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['singleplayer', 'platformer', 'difficult', 'story-rich', 'low-end'],
    isFree: false, price: '$19.99', developer: 'Extremely OK Games', publisher: 'Extremely OK Games', releaseYear: 2018, views: 5800,
    screenshots: [],
  },
  {
    title: 'Manor Lords',
    description: 'Medieval city-builder with gorgeous visuals and real-time strategic battles. Build your settlement from a village to a thriving city.',
    genre: 'Strategy',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1363080/header.jpg',
    rating: 9.4,
    trailerUrl: '7hX8aFCFpkU',
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-4670K', ram: '8 GB', gpu: 'NVIDIA GeForce GTX 1050 Ti', storage: '15 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1363080/',
    downloadLinks: { pc: 'https://store.steampowered.com/app/1363080/', android: '', ios: '', console: '' },
    downloadSource: 'Steam',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['singleplayer', 'city-builder', 'medieval', 'RTS'],
    isFree: false, price: '$39.99', developer: 'Slavic Magic', publisher: 'Hooded Horse', releaseYear: 2024, views: 12000, isTrending: true,
    screenshots: [],
  },
  {
    title: 'EA SPORTS FC 26',
    description: 'The definitive football simulation for the 2026 season, featuring HyperMotion V technology and immersive career and ultimate team modes.',
    genre: 'Sports',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2195250/header.jpg',
    rating: 8.6,
    trailerUrl: 'kzSs2IorP0U',
    systemRequirements: { os: 'Windows 11', cpu: 'Intel Core i7-6700K', ram: '12 GB', gpu: 'NVIDIA GTX 1660', storage: '100 GB' },
    officialDownloadLink: 'https://www.ea.com/games/ea-sports-fc',
    downloadLinks: { pc: 'https://www.ea.com/games/ea-sports-fc', android: '', ios: '', console: 'https://www.ea.com/games/ea-sports-fc' },
    downloadSource: 'Official Site',
    playUrl: '',
    isBrowserPlayable: false,
    tags: ['multiplayer', 'football', 'competitive', 'trending'],
    isFree: false, price: '$69.99', developer: 'EA Vancouver', publisher: 'EA Sports', releaseYear: 2025, views: 25000, isTrending: true,
    screenshots: [],
  },
];

module.exports = { games };
