const games = [
  // ─── ACTION ────────────────────────────────────────────────────────────
  {
    title: 'Grand Theft Auto V',
    description: 'Open-world crime sandbox with driving, shooting, and deep side activities. The definitive Los Santos experience.',
    genre: 'Action',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg',
    rating: 9.5,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-3470', ram: '8 GB', gpu: 'NVIDIA GTX 660', storage: '92 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/',
    downloadSource: 'Steam',
    tags: ['multiplayer', 'open-world', 'crime', 'action'],
    isFree: false, price: '$29.99', developer: 'Rockstar North', publisher: 'Rockstar Games', releaseYear: 2015, views: 12000,
  },
  {
    title: 'Cyberpunk 2077',
    description: 'Futuristic open-world RPG with fast-paced combat and deep story choices. Explore the vibrant Night City.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
    rating: 9.0,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i7-6700K', ram: '12 GB', gpu: 'NVIDIA GTX 1060', storage: '70 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1091500/Cyberpunk_2077/',
    downloadSource: 'Steam',
    tags: ['open-world', 'RPG', 'futuristic', 'singleplayer'],
    isFree: false, price: '$59.99', developer: 'CD Projekt Red', publisher: 'CD Projekt', releaseYear: 2020, views: 9500,
  },
  {
    title: 'Hades',
    description: 'Fast-paced roguelike dungeon-crawler with stylish combat and great writing. Defy the god of the dead.',
    genre: 'Action',
    platform: ['PC', 'Console', 'Mobile'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
    rating: 9.8,
    systemRequirements: { os: 'Windows 7 SP1', cpu: 'Intel Core i5-2400', ram: '8 GB', gpu: 'NVIDIA GTX 850M', storage: '15 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1145360/Hades/',
    downloadSource: 'Steam',
    tags: ['roguelike', 'singleplayer', 'offline', 'indie'],
    isFree: false, price: '$24.99', developer: 'Supergiant Games', publisher: 'Supergiant Games', releaseYear: 2020, views: 8800,
  },
  {
    title: 'Genshin Impact',
    description: 'Anime-style open-world action RPG with gacha mechanics and co-op exploration across Teyvat.',
    genre: 'RPG',
    platform: ['PC', 'Mobile', 'Console', 'Cross-Platform'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Genshin_Impact_logo.png',
    rating: 8.7,
    systemRequirements: { os: 'Windows 7 SP1 64-bit', cpu: 'Intel Core i7', ram: '16 GB', gpu: 'NVIDIA GTX 1060', storage: '30 GB' },
    officialDownloadLink: 'https://genshin.hoyoverse.com/en/home',
    downloadSource: 'Official Site',
    tags: ['free', 'multiplayer', 'open-world', 'anime'],
    isFree: true, price: 'Free', developer: 'miHoYo', publisher: 'HoYoverse', releaseYear: 2020, views: 15000,
  },
  {
    title: 'PUBG Mobile',
    description: 'Mobile-focused battle-royale shooter set in large open maps. The ultimate survival experience on the go.',
    genre: 'Battle Royale',
    platform: ['Mobile'],
    imageUrl: 'https://play-lh.googleusercontent.com/JRd0v_H_tI17sEEO_2_B68wSndGvVdaq19-F_mreP8DVsYw.jpg',
    rating: 8.4,
    systemRequirements: { os: 'Android 5.1 / iOS 11', cpu: 'Snapdragon 625', ram: '2 GB', gpu: 'Any', storage: '2 GB' },
    officialDownloadLink: 'https://play.google.com/store/apps/details?id=com.tencent.ig',
    downloadSource: 'Play Store',
    tags: ['free', 'multiplayer', 'battle-royale', 'mobile'],
    isFree: true, price: 'Free', developer: 'LightSpeed & Quantum Studio', publisher: 'Tencent Games', releaseYear: 2018, views: 11000,
  },

  // ─── RPG (Role-Playing Games) ──────────────────────────────────────────
  {
    title: 'Elden Ring',
    description: 'Souls-style open-world RPG with deep lore, tough combat, and exploration. Rise, Tarnished.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
    rating: 9.7,
    systemRequirements: { os: 'Windows 10/11', cpu: 'Intel Core i5-8400', ram: '12 GB', gpu: 'NVIDIA GTX 1060', storage: '60 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1245620/ELDEN_RING/',
    downloadSource: 'Steam',
    tags: ['multiplayer', 'open-world', 'souls-like', 'difficult'],
    isFree: false, price: '$59.99', developer: 'FromSoftware', publisher: 'Bandai Namco', releaseYear: 2022, views: 13000,
  },
  {
    title: 'The Witcher 3: Wild Hunt',
    description: 'Story-driven fantasy RPG with vast open world and rich side quests. Become Geralt of Rivia.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
    rating: 9.8,
    systemRequirements: { os: 'Windows 7/8/10', cpu: 'Intel Core i5-2500K', ram: '6 GB', gpu: 'NVIDIA GTX 660', storage: '50 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'open-world', 'story-rich', 'fantasy'],
    isFree: false, price: '$39.99', developer: 'CD Projekt Red', publisher: 'CD Projekt', releaseYear: 2015, views: 10500,
  },
  {
    title: 'Diablo IV',
    description: 'Dark fantasy ARPG with loot-driven progression and online co-op. Return to Sanctuary.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2344520/header.jpg',
    rating: 8.9,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-2500K', ram: '8 GB', gpu: 'NVIDIA GTX 660', storage: '90 GB' },
    officialDownloadLink: 'https://diablo4.blizzard.com/',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'action-RPG', 'dark-fantasy', 'loot'],
    isFree: false, price: '$69.99', developer: 'Blizzard Entertainment', publisher: 'Blizzard Entertainment', releaseYear: 2023, views: 9200,
  },
  {
    title: 'Sea of Stars',
    description: 'Modern retro-style RPG with pixel art and tactical turn-based combat. A love letter to the classics.',
    genre: 'RPG',
    platform: ['PC', 'Console', 'Mobile'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1244090/header.jpg',
    rating: 9.2,
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core 2 Duo E8400', ram: '4 GB', gpu: 'NVIDIA GeForce 9600 GT', storage: '5 GB' },
    officialDownloadLink: 'https://www.seaofstarsgame.com/',
    downloadSource: 'Official Site',
    tags: ['indie', 'turn-based', 'pixel-art', 'story-focused'],
    isFree: false, price: '$34.99', developer: 'Sabotage Studio', publisher: 'Sabotage Studio', releaseYear: 2023, views: 5600,
  },
  {
    title: 'Ni-no-Kuni II: Revenant Kingdom',
    description: 'Charming fantasy JRPG with kingdom-building and real-time battles. Reclaim your throne.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/589360/header.jpg',
    rating: 8.5,
    systemRequirements: { os: 'Windows 7 SP1 64bit', cpu: 'Intel Core i5-4460', ram: '4 GB', gpu: 'NVIDIA GeForce GTX 750 Ti', storage: '40 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/589360/Ni_no_Kuni_II_Revenant_Kingdom/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'JRPG', 'fantasy', 'kingdom-building'],
    isFree: false, price: '$59.99', developer: 'Level-5', publisher: 'Bandai Namco', releaseYear: 2018, views: 4200,
  },

  // ─── FPS (First-Person Shooter) ────────────────────────────────────────
  {
    title: 'Call of Duty: Warzone',
    description: 'Large-scale free-to-play battle-royale within the CoD universe. Drop in and survive.',
    genre: 'Battle Royale',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1962660/header.jpg',
    rating: 8.2,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i3-6100', ram: '8 GB', gpu: 'NVIDIA GTX 960', storage: '125 GB' },
    officialDownloadLink: 'https://www.callofduty.com/warzone',
    downloadSource: 'Official Site',
    tags: ['free', 'multiplayer', 'battle-royale', 'shooter'],
    isFree: true, price: 'Free', developer: 'Infinity Ward', publisher: 'Activision', releaseYear: 2020, views: 14000,
  },
  {
    title: 'Valorant',
    description: '5v5 hero-based tactical shooter where precise gunplay meets unique agent abilities.',
    genre: 'Shooter',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cmsassets.rgpub.io/sanity/images/dsfx7636/news/ea9e6da6b0e2f1e1fc38e78d6b36e2bc5a5d4b00-1920x1080.jpg',
    rating: 9.0,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel i3-4150', ram: '4 GB', gpu: 'NVIDIA GT 730', storage: '30 GB' },
    officialDownloadLink: 'https://playvalorant.com/',
    downloadSource: 'Official Site',
    tags: ['free', 'multiplayer', 'competitive', 'tactical'],
    isFree: true, price: 'Free', developer: 'Riot Games', publisher: 'Riot Games', releaseYear: 2020, views: 15500,
  },
  {
    title: 'Halo: The Master Chief Collection',
    description: 'Compilation of classic Halo titles with modern matchmaking and stunning 4K visuals.',
    genre: 'Shooter',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/976730/header.jpg',
    rating: 9.4,
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core i7-870', ram: '8 GB', gpu: 'NVIDIA GTX 560 Ti', storage: '160 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/',
    downloadSource: 'Steam',
    tags: ['multiplayer', 'classic', 'sci-fi', 'singleplayer'],
    isFree: false, price: '$39.99', developer: '343 Industries', publisher: 'Xbox Game Studios', releaseYear: 2019, views: 7200,
  },
  {
    title: 'Metro Exodus',
    description: 'Atmospheric post-apocalyptic FPS with survival and story focus. Escape the ruins of Moscow.',
    genre: 'Shooter',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/412020/header.jpg',
    rating: 9.1,
    systemRequirements: { os: 'Windows 10', cpu: 'Intel Core i5-4440', ram: '8 GB', gpu: 'NVIDIA GTX 1050', storage: '59 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/412020/Metro_Exodus/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'story-rich', 'post-apocalyptic', 'survival'],
    isFree: false, price: '$29.99', developer: '4A Games', publisher: 'Deep Silver', releaseYear: 2019, views: 6100,
  },
  {
    title: 'Doom Eternal',
    description: 'Fast-paced supernatural shooter with heavy combat and movement. Rip and tear until it is done.',
    genre: 'Shooter',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/782330/header.jpg',
    rating: 9.6,
    systemRequirements: { os: 'Windows 7/10 64-bit', cpu: 'Intel Core i5 @ 3.3 GHz', ram: '8 GB', gpu: 'NVIDIA GTX 1050 Ti', storage: '50 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/782330/DOOM_Eternal/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'fast-paced', 'action', 'demons'],
    isFree: false, price: '$39.99', developer: 'id Software', publisher: 'Bethesda Softworks', releaseYear: 2020, views: 8900,
  },

  // ─── RACING ────────────────────────────────────────────────────────────
  {
    title: 'Forza Horizon 5',
    description: 'Vibrant open-world racing festival with cars, events, and online modes in the heart of Mexico.',
    genre: 'Racing',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg',
    rating: 9.3,
    systemRequirements: { os: 'Windows 10', cpu: 'Intel i5-4460', ram: '8 GB', gpu: 'NVIDIA GTX 970', storage: '110 GB' },
    officialDownloadLink: 'https://www.xbox.com/en-US/games/forza-horizon-5',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'open-world', 'racing', 'cars'],
    isFree: false, price: '$59.99', developer: 'Playground Games', publisher: 'Xbox Game Studios', releaseYear: 2021, views: 11500,
  },
  {
    title: 'Forza Horizon 6 (2026)',
    description: 'The next evolution of the Horizon festival, set in the neon-lit streets and rural landscapes of Japan.',
    genre: 'Racing',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg',
    rating: 9.5,
    systemRequirements: { os: 'Windows 11', cpu: 'Intel i7-11700K', ram: '16 GB', gpu: 'NVIDIA RTX 3070', storage: '120 GB' },
    officialDownloadLink: 'https://forzamotorsport.net/',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'open-world', 'next-gen', 'trending'],
    isFree: false, price: '$69.99', developer: 'Playground Games', publisher: 'Xbox Game Studios', releaseYear: 2026, views: 18000,
    isTrending: true,
  },
  {
    title: 'Rocket League',
    description: 'Soccer with rocket-powered cars! High-flying, competitive cross-platform action.',
    genre: 'Sports',
    platform: ['PC', 'Console', 'Cross-Platform'],
    imageUrl: 'https://cdn2.unrealengine.com/rocket-league-1920x1080-1920x1080-971712992.jpg',
    rating: 9.1,
    systemRequirements: { os: 'Windows 7 or later', cpu: '2.5 GHz Dual Core', ram: '4 GB', gpu: 'NVIDIA GTX 760', storage: '20 GB' },
    officialDownloadLink: 'https://www.rocketleague.com/',
    downloadSource: 'Official Site',
    tags: ['free', 'multiplayer', 'competitive', 'sports'],
    isFree: true, price: 'Free', developer: 'Psyonix', publisher: 'Psyonix', releaseYear: 2015, views: 13000,
  },
  {
    title: 'Trackmania',
    description: 'Level-based arcade racing with fast times, insane loops, and online leaderboards.',
    genre: 'Racing',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2225070/header.jpg',
    rating: 8.4,
    systemRequirements: { os: 'Windows 10', cpu: 'Intel Core i5-2500K', ram: '8 GB', gpu: 'NVIDIA GeForce GTX 660', storage: '2 GB' },
    officialDownloadLink: 'https://www.trackmania.com/',
    downloadSource: 'Official Site',
    tags: ['free', 'multiplayer', 'racing', 'competitive'],
    isFree: true, price: 'Free', developer: 'Ubisoft Nadeo', publisher: 'Ubisoft', releaseYear: 2020, views: 4800,
  },
  {
    title: 'CarX Street',
    description: 'Mobile drift-style racing with realistic physics, custom cars, and a massive open-world city.',
    genre: 'Racing',
    platform: ['Mobile'],
    imageUrl: 'https://play-lh.googleusercontent.com/7A_L9_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8_X_8.jpg',
    rating: 8.0,
    systemRequirements: { os: 'Android 9.0 / iOS 13', cpu: 'Snapdragon 845', ram: '4 GB', gpu: 'Any', storage: '4 GB' },
    officialDownloadLink: 'https://play.google.com/store/apps/details?id=com.carxtech.sr',
    downloadSource: 'Play Store',
    tags: ['free', 'multiplayer', 'mobile', 'drifting'],
    isFree: true, price: 'Free', developer: 'CarX Technologies', publisher: 'CarX Technologies', releaseYear: 2022, views: 7500,
  },

  // ─── STRATEGY ──────────────────────────────────────────────────────────
  {
    title: 'Civilization VI',
    description: 'Turn-based empire-building with deep diplomacy, tech progression, and historical leaders.',
    genre: 'Strategy',
    platform: ['PC', 'Mobile', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/281990/header.jpg',
    rating: 9.0,
    systemRequirements: { os: 'Windows 7/8/10 64-bit', cpu: 'Intel Core i3 2.5 Ghz', ram: '4 GB', gpu: '1GB DirectX 11 Video Card', storage: '12 GB' },
    officialDownloadLink: 'https://civilization.com/',
    downloadSource: 'Official Site',
    tags: ['multiplayer', '4X', 'turn-based', 'historical'],
    isFree: false, price: '$59.99', developer: 'Firaxis Games', publisher: '2K Games', releaseYear: 2016, views: 9800,
  },
  {
    title: 'XCOM 2',
    description: 'Turn-based tactical combat against alien occupation. Lead the resistance and reclaim Earth.',
    genre: 'Strategy',
    platform: ['PC', 'Console', 'Mobile'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/268500/header.jpg',
    rating: 8.8,
    systemRequirements: { os: 'Windows 7 64-bit', cpu: 'Intel Core 2 Duo E4700', ram: '4 GB', gpu: 'NVIDIA GeForce GTX 460', storage: '45 GB' },
    officialDownloadLink: 'https://xcom.com/',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'tactical', 'aliens', 'difficult'],
    isFree: false, price: '$59.99', developer: 'Firaxis Games', publisher: '2K Games', releaseYear: 2016, views: 5400,
  },
  {
    title: 'Manor Lords',
    description: 'Medieval city-builder with real-time battles and complex social and economic simulation.',
    genre: 'Strategy',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1363080/header.jpg',
    rating: 9.4,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-4670K', ram: '8 GB', gpu: 'NVIDIA GeForce GTX 1050 Ti', storage: '15 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1363080/Manor_Lords/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'city-builder', 'medieval', 'RTS'],
    isFree: false, price: '$39.99', developer: 'Slavic Magic', publisher: 'Hooded Horse', releaseYear: 2024, views: 12000,
    isTrending: true,
  },
  {
    title: 'StarCraft II',
    description: 'Iconic real-time strategy game with intense competitive multiplayer and a gripping sci-fi story.',
    genre: 'Strategy',
    platform: ['PC'],
    imageUrl: 'https://blz-contentstack-images.akamaized.net/v3/assets/blt7e492ca447dd8451/blt6e3c...jpg',
    rating: 9.3,
    systemRequirements: { os: 'Windows 7 / 8 / 10', cpu: 'Intel Core i5', ram: '4 GB', gpu: 'NVIDIA GeForce GTX 650', storage: '30 GB' },
    officialDownloadLink: 'https://starcraft2.com/',
    downloadSource: 'Official Site',
    tags: ['free', 'multiplayer', 'RTS', 'competitive'],
    isFree: true, price: 'Free', developer: 'Blizzard Entertainment', publisher: 'Blizzard Entertainment', releaseYear: 2010, views: 8200,
  },
  {
    title: 'Triangle Strategy',
    description: 'Story-driven turn-based tactical RPG with branching paths and difficult moral choices.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1850560/header.jpg',
    rating: 8.7,
    systemRequirements: { os: 'Windows 8.1 / 10 64-bit', cpu: 'AMD Ryzen 3 1200 / Intel Core i5-4460', ram: '8 GB', gpu: 'NVIDIA GeForce GTX 760', storage: '10 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/1850560/TRIANGLE_STRATEGY/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'turn-based', 'tactical', 'story-rich'],
    isFree: false, price: '$59.99', developer: 'Square Enix', publisher: 'Square Enix', releaseYear: 2022, views: 3900,
  },

  // ─── SPORTS ────────────────────────────────────────────────────────────
  {
    title: 'EA SPORTS FC 26',
    description: 'The definitive football experience for the 2026 season, featuring HyperMotion V and deep career modes.',
    genre: 'Sports',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2195250/header.jpg',
    rating: 8.6,
    systemRequirements: { os: 'Windows 11', cpu: 'Intel Core i7-6700K', ram: '12 GB', gpu: 'NVIDIA GTX 1660', storage: '100 GB' },
    officialDownloadLink: 'https://www.ea.com/games/ea-sports-fc',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'football', 'competitive', 'trending'],
    isFree: false, price: '$69.99', developer: 'EA Vancouver', publisher: 'EA Sports', releaseYear: 2025, views: 25000,
    isTrending: true,
  },
  {
    title: 'NBA 2K26',
    description: 'Experience professional basketball with updated rosters, stunning graphics, and the deep MyCareer mode.',
    genre: 'Sports',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2738600/header.jpg',
    rating: 7.9,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-4430', ram: '8 GB', gpu: 'NVIDIA GTX 1060', storage: '150 GB' },
    officialDownloadLink: 'https://nba.2k.com/',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'basketball', 'competitive'],
    isFree: false, price: '$69.99', developer: 'Visual Concepts', publisher: '2K Games', releaseYear: 2025, views: 12000,
  },
  {
    title: 'Tony Hawk’s Pro Skater 1+2',
    description: 'Drop back in with the most iconic skateboarding games ever made, fully remastered in HD.',
    genre: 'Sports',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2390430/header.jpg',
    rating: 9.3,
    systemRequirements: { os: 'Windows 10', cpu: 'Intel Core i3-4340', ram: '8 GB', gpu: 'NVIDIA GTX 660', storage: '24 GB' },
    officialDownloadLink: 'https://www.tonyhawkthegame.com/',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'skateboarding', 'multiplayer', 'classic'],
    isFree: false, price: '$39.99', developer: 'Vicarious Visions', publisher: 'Activision', releaseYear: 2020, views: 6500,
  },
  {
    title: 'Nintendo Switch Sports',
    description: 'Get moving with Soccer, Volleyball, Bowling, Tennis, Badminton, and Chambara (Swordplay) using Joy-Con controllers.',
    genre: 'Sports',
    platform: ['Console'],
    imageUrl: 'https://assets.nintendo.com/image/upload/f_auto/q_auto/v1/ncom/en_US/games/switch/n/nintendo-switch-sports-switch/hero',
    rating: 8.2,
    systemRequirements: { os: 'Nintendo Switch OS', cpu: 'NVIDIA Tegra X1', ram: '4 GB', gpu: 'Custom Maxwell', storage: '3 GB' },
    officialDownloadLink: 'https://www.nintendo.com/store/products/nintendo-switch-sports-switch/',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'motion-controls', 'family-friendly'],
    isFree: false, price: '$39.99', developer: 'Nintendo EPD', publisher: 'Nintendo', releaseYear: 2022, views: 15000,
  },

  // ─── INDIE ─────────────────────────────────────────────────────────────
  {
    title: 'Hollow Knight',
    description: 'Challenging 2D Metroidvania with hand-drawn art. Explore a vast underground kingdom of bugs and heroes.',
    genre: 'Indie',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
    rating: 9.6,
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core i5', ram: '4 GB', gpu: 'NVIDIA GTX 560', storage: '9 GB' },
    officialDownloadLink: 'https://store.steampowered.com/app/367520/Hollow_Knight/',
    downloadSource: 'Steam',
    tags: ['singleplayer', 'metroidvania', 'difficult', 'low-end'],
    isFree: false, price: '$14.99', developer: 'Team Cherry', publisher: 'Team Cherry', releaseYear: 2017, views: 9200,
  },
  {
    title: 'Celeste',
    description: 'Challenging pixel-art platformer with an emotional story about overcoming personal struggles.',
    genre: 'Indie',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg',
    rating: 9.5,
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core i3 @ 2.0 GHz', ram: '2 GB', gpu: 'Intel HD 4000', storage: '1.2 GB' },
    officialDownloadLink: 'http://www.celestegame.com/',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'platformer', 'difficult', 'story-rich'],
    isFree: false, price: '$19.99', developer: 'Extremely OK Games', publisher: 'Extremely OK Games', releaseYear: 2018, views: 5800,
  },
  {
    title: 'Dead Cells',
    description: 'Fast-paced rogue-lite action-platformer. No checkpoints. Kill, die, learn, repeat.',
    genre: 'Indie',
    platform: ['PC', 'Console', 'Mobile'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/588650/header.jpg',
    rating: 9.3,
    systemRequirements: { os: 'Windows 7', cpu: 'Intel i5 @ 3.0 GHz', ram: '4 GB', gpu: 'NVIDIA GTX 460', storage: '500 MB' },
    officialDownloadLink: 'https://dead-cells.com/',
    downloadSource: 'Official Site',
    tags: ['rogue-lite', 'singleplayer', 'action', 'challenging'],
    isFree: false, price: '$24.99', developer: 'Motion Twin', publisher: 'Motion Twin', releaseYear: 2018, views: 7600,
  },
  {
    title: 'Spiritfarer',
    description: 'Relaxing management game about guiding spirits to the afterlife. A cozy experience about saying goodbye.',
    genre: 'Simulation',
    platform: ['PC', 'Console', 'Mobile'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/972660/header.jpg',
    rating: 9.4,
    systemRequirements: { os: 'Windows 7', cpu: 'Intel Core i3 @ 2.0 GHz', ram: '4 GB', gpu: 'NVIDIA GeForce GTX 260', storage: '7 GB' },
    officialDownloadLink: 'https://thunderlotusgames.com/spiritfarer/',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'cozy', 'story-rich', 'emotional'],
    isFree: false, price: '$29.99', developer: 'Thunder Lotus Games', publisher: 'Thunder Lotus Games', releaseYear: 2020, views: 4200,
  },

  // ─── OPEN WORLD ────────────────────────────────────────────────────────
  {
    title: 'Grand Theft Auto VI',
    description: 'The next generation of open-world crime. Return to Vice City in the most anticipated game of the decade.',
    genre: 'Action',
    platform: ['Console', 'PC'],
    imageUrl: 'https://media-rockstargames-com.akamaized.net/m0/gta-vi/og-image.jpg',
    rating: 9.9,
    systemRequirements: { os: 'Windows 11', cpu: 'Intel Core i9-12900K', ram: '32 GB', gpu: 'NVIDIA RTX 4080', storage: '200 GB' },
    officialDownloadLink: 'https://www.rockstargames.com/VI',
    downloadSource: 'Official Site',
    tags: ['multiplayer', 'open-world', 'next-gen', 'trending'],
    isFree: false, price: '$79.99', developer: 'Rockstar Games', publisher: 'Rockstar Games', releaseYear: 2026, views: 100000,
    isTrending: true,
  },
  {
    title: 'Horizon Forbidden West',
    description: 'Explore distant lands, fight bigger and more awe-inspiring machines, and encounter astonishing new tribes in a far-future world.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2420110/header.jpg',
    rating: 9.2,
    systemRequirements: { os: 'Windows 10', cpu: 'Intel Core i5-8600', ram: '16 GB', gpu: 'NVIDIA RTX 3060', storage: '150 GB' },
    officialDownloadLink: 'https://www.playstation.com/en-us/games/horizon-forbidden-west/',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'open-world', 'sci-fi', 'action-RPG'],
    isFree: false, price: '$59.99', developer: 'Guerrilla Games', publisher: 'Sony Interactive Entertainment', releaseYear: 2024, views: 15600,
  },
  {
    title: 'Dragon’s Dogma 2',
    description: 'Embark on a grand adventure as the Arisen in a deep, explorable fantasy world. Pawns await your command.',
    genre: 'RPG',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2054970/header.jpg',
    rating: 8.8,
    systemRequirements: { os: 'Windows 10 64-bit', cpu: 'Intel Core i5-10600', ram: '16 GB', gpu: 'NVIDIA RTX 2080', storage: '100 GB' },
    officialDownloadLink: 'https://www.dragonsdogma.com/2/',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'open-world', 'fantasy', 'action-RPG'],
    isFree: false, price: '$69.99', developer: 'Capcom', publisher: 'Capcom', releaseYear: 2024, views: 9800,
  },
  {
    title: 'Assassin’s Creed IV: Black Flag (Remastered)',
    description: 'The golden age of piracy returns with enhanced visuals and updated mechanics. Rule the high seas.',
    genre: 'Action',
    platform: ['PC', 'Console'],
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/24200/header.jpg',
    rating: 9.4,
    systemRequirements: { os: 'Windows 10', cpu: 'Intel Core i5-6600', ram: '8 GB', gpu: 'NVIDIA GTX 1060', storage: '50 GB' },
    officialDownloadLink: 'https://www.ubisoft.com/en-us/game/assassins-creed/iv-black-flag',
    downloadSource: 'Official Site',
    tags: ['singleplayer', 'open-world', 'pirate', 'stealth'],
    isFree: false, price: '$39.99', developer: 'Ubisoft Montreal', publisher: 'Ubisoft', releaseYear: 2026, views: 12400,
  },
];

module.exports = { games };
